name: Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: npm install
        run: |
          npm install
        working-directory: electron-frontend

      - name: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package-ci
          npm run lint
          npm run ts
        working-directory: electron-frontend

# Failing beacuse virtual framebuffer not installed
#          npm run build-e2e
#          npm test-e2e
