# electron frontend test
name: Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        working-directory: electron-frontend

    strategy:
      matrix:
        os: [macos-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package-ci
          npm run lint
          npm run ts
